version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql # Optional SQL seed file

  # Backend Service (Node.js + Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    environment:
      DB_USER: your_username
      DB_PASSWORD: your_password
      DB_NAME: your_database_name
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  # Frontend Service (React Native with Metro Bundler)
  frontend:
    build:
      context: ./react-native
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "8081:8081"  # Exposes Metro bundler
    command: ["npm", "start"]
    volumes:
      - ./react-native:/app  # Mounts local react-native folder

volumes:
  postgres_data:
