version: '3.8'

services:
  # Python Telegram Bot
  telegram-bot:
    build:
      context: ./telegram_bot
      dockerfile: ./Dockerfile
    container_name: telegram-journal-bot
    volumes:
      - ./telegram_bot/data:/app/data
      - ./telegram_bot/logs:/app/logs
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - USERS_FILE=data/users.json
      - CHECK_INTERVAL=3600
      - PROMPT_HOUR=9
      - PROMPT_DAY=0
      - MAX_HISTORY=5
    restart: unless-stopped

  # Firebase Functions
  firebase:
    build:
      context: ./firebase/functions
      dockerfile: ./Dockerfile
    container_name: firebase-functions
    volumes:
      - ./firebase/functions/src:/app/src
      - ./firebase/functions/lib:/app/lib
      - ./firebase/.firebaserc:/app/.firebaserc:ro
      - ./firebase/firebase.json:/firebase.json:ro
      - ./firebase/functions/.runtimeconfig.json:/app/.runtimeconfig.json:ro
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - PORT=8080
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
    ports:
      - "8080:8080"