FROM node:23-slim

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install
RUN npm install -g nodemon ts-node

COPY src/ ./src/
COPY public/ ./public/

EXPOSE 3000

CMD ["npm", "run", "dev"]