services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thyknow
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/thyknow
      - TIMEZONE=Asia/Singapore
      - VALIDATE_TELEGRAM_REQUESTS=false
      - BASE_URL=http://localhost:3000
    ports:
      - "3000:3000"

volumes:
  postgres-data: