[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "node dist/src/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5